# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

env:
  global:
    - CC_TEST_REPORTER_ID=a6c808a99cff3b7f3aa5942cca8d168018b41e5df80a8b3d24831327c7deff2e
language: python
python:
  - 3.6
  - 3.5
  - 3.4

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# command to run tests, e.g. python setup.py test
script: tox

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then ./cc-test-reporter before-build; fi

after_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
