# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py
language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"
  - "pypy3.5-6.0"
env:
  global:
    - CC_TEST_REPORTER_ID=88fae959f68f3139aeeb3cd64ce11841115a336fdfc91b7cecd52958acb4d3e9
  matrix:
    - DJANGO_VERSION=111
    - DJANGO_VERSION=21
    - DJANGO_VERSION=22
matrix:
  fast_finish: true
  allow_failures:
    - python: "3.8-dev"
      env: DJANGO_VERSION=22
  exclude:
    # Only Django 3.x will support Python 3.8, so only test latest version
    # until 3.0 comes out
    - python: "3.8-dev"
      env: DJANGO_VERSION=111
    - python: "3.8-dev"
      env: DJANGO_VERSION=21
  include:
    - python: "3.7"
      env: DJANGO_VERSION=22-extras

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis
  - pip install -U coveralls

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

before_script:
  - PY_VERSION=${TRAVIS_PYTHON_VERSION/./}
  - PY_VERSION=${PY_VERSION/-dev/}
  - PY_VERSION=${PY_VERSION/pypy/py}
  - PY_VERSION=${PY_VERSION/py35-6.0/py3}
  - export TOX_ENV="py$PY_VERSION-dj$DJANGO_VERSION"
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then ./cc-test-reporter before-build; fi

after_success:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then coveralls; fi

after_script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then coverage xml; fi
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TOX_ENV" = "py37-dj22-extras" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t coverage.py; fi
